// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPldP7dOrpGTVvPMFbc-gLuBkEHRLb76s',
    appId: '1:652793822272:web:9569a5550565c7e32073a5',
    messagingSenderId: '652793822272',
    projectId: 'flutter-chat-app-a5e53',
    authDomain: 'flutter-chat-app-a5e53.firebaseapp.com',
    storageBucket: 'flutter-chat-app-a5e53.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7g6Gri_2XQI_pd4TgfXxSa7wBpa0krqI',
    appId: '1:652793822272:android:503231864a4a60912073a5',
    messagingSenderId: '652793822272',
    projectId: 'flutter-chat-app-a5e53',
    storageBucket: 'flutter-chat-app-a5e53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNVtv2BjS7Hvdr3m0nctiHS0FTePJn5gs',
    appId: '1:652793822272:ios:fb5b459e8a9f16522073a5',
    messagingSenderId: '652793822272',
    projectId: 'flutter-chat-app-a5e53',
    storageBucket: 'flutter-chat-app-a5e53.appspot.com',
    iosClientId: '652793822272-pssi7t6ubp75i6f2bee35sq9sctkpigc.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNVtv2BjS7Hvdr3m0nctiHS0FTePJn5gs',
    appId: '1:652793822272:ios:1b9c707a69307ac12073a5',
    messagingSenderId: '652793822272',
    projectId: 'flutter-chat-app-a5e53',
    storageBucket: 'flutter-chat-app-a5e53.appspot.com',
    iosClientId: '652793822272-da0i841durf2r8sgu7fulbnli6dhq22h.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
